# -*- coding: utf-8 -*-
"""Exercicios_Praticos-7a-Operadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vaNzU-weXwa9NGl6HE1yT1cZyPxLOucd

# Exercício 1
"""

a = 5
b = 28

a == b

"""# Exercício 2"""

nota1 = 8
nota2 = 9.5
nota3 = 10
nota4 = 8.5
nota5 = 9

media = (nota1 + nota2 + nota3 + nota4 + nota5)/5
print(media)

"""# Exercicio 3"""

base = 2
exp = 3

print(2 ** 3)

"""# Exercicio 4"""

num1 = 98
num2 = 5

(num1 % num2) == 0

"""# Exercicio 5"""

num1 // num2

"""# Exercicio 6"""

tam_seq_bio = 67
tam_seq_bio >= 5 and tam_seq_bio <= 30

"""# Exercicio 7"""

tam_se_bio = 67
tam_seq_bio > 5 and tam_seq_bio <= 30

"""# Exercicio 8"""

aa_lista = ['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', \
'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']

letra = 'C'

letra in aa_lista

"""# Exercicio 9"""

pos=['H', 'K', 'R']
neg=['D', 'E']
AA = 'C'

print('Carregado?', AA in pos or AA in neg)
print('Neutro?', (not AA in pos) and (not AA in neg))

